name = "v"
main = "src/worker.js"
compatibility_date = "2024-08-01"
account_id = "a41b556e5cb967da7d49d43379f9662f"

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "clips"

[stream]
binding = "STREAM"

[vars]
CLOUDFLARE_ACCOUNT_ID = "a41b556e5cb967da7d49d43379f9662f"
SITE_URL = "https://v.kdnzxcv777.workers.dev"
